In [1]:
import pandas as pd

In [2]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df_by_passenger_id = df.set_index('PassengerId')

In [5]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df_by_name = df.set_index('Name')

In [7]:
df_by_name.head(1)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.25,NaN,S

In [8]:
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

# Are Subsets Views or Copies in Pandas?

In pandas, whether you get a view (linked to original DataFrame) or a copy (independent) 
depends on how you slice or filter — and it’s not always obvious.

- .iloc always returns a copy (safe, independent subset.)
- .loc may return a view (especially if indexing on labels)
    ```bash
    subset = df.loc[df['Sex'] == 'male']
    This is like the earlier filtering — might be a view.

    so..
    subset = df.loc[df['Sex'] == 'male'].copy()

    ```

| Situation                          | View or Copy? | Should you use `.copy()`? |
| ---------------------------------- | ------------- | ------------------------- |
| `.iloc[]` slicing                  | Mostly Copy   | Optional                  |
| `.loc[]` slicing                   | May be View   | Recommended               |
| Filtering with condition `df[...]` | May be View   | Recommended               |
| You plan to modify the subset      | Use `.copy()` | YES                       |

In [ ]:
# instead of below

subset = df[df['Sex'] == 'male']
subset['Age'] = subset['Age'] + 1

# SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

In [11]:
subset = df[df['Sex'] == 'male'].copy()
subset['Age'] += 1

In [12]:
subset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,29.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,26.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,28.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,27.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,33.0,0,0,370376,7.7500,NaN,Q

In [13]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Set Index vs Re - index

| Feature       | `set_index()`                               | `reindex()`                                          |
| ------------- | ------------------------------------------- | ---------------------------------------------------- |
| What it does  | **Moves a column** to become the index      | **Changes the row/column labels** of a DataFrame     |
| Main Use Case | Change the row labels using existing column | Match to new labels, add/remove/reorder rows/columns |
| Affects index | Yes – creates a **new index from a column** | Yes – but just **remaps or aligns to new index**     |
| Adds NaNs?    | No – only restructures                      | Yes – can insert NaNs for new labels                 |

In [14]:
# NAN -> Not a number

# 1. set_index() — Use a column as the new index

In [15]:
df_by_name = df.set_index('Name')
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])  # Now 'Name' is index

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [16]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df_by_name = df_by_name.reset_index()

In [18]:
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

# 2. reindex() — Conform to a new index/column structure

In [19]:
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [20]:
sales_feb = pd.DataFrame({
    'Sales': [260, 310]
}, index=['Store_A', 'Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

❌ Problem: Indexes are mismatched!

You cannot safely do operations like subtraction or direct comparison unless indexes are aligned.

✅ 🛠 Solution: Use reindex() to align!

In [22]:
common_index = sales_jan.index

print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [23]:
sales_feb_aligned = sales_feb.reindex(common_index)

sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [25]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [26]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0)

sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [27]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

# For column

In [28]:
source_a = pd.DataFrame({
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1000, 500, 800],
    'Stock': [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [29]:
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [33]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

In [32]:
stock_diff = source_a['Stock'] - aligned_b['Stock']

stock_diff

0     30
1     50
2    100
Name: Stock, dtype: int64

# Iteration in Pandas

In pandas, iteration refers to looping over rows or columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop — for example, for conditional logic, debugging, or generating complex values.

In [34]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

In [35]:
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai

In [36]:
for index, row in df.iterrows():
    print(f"{index}: {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0: Alice lives in Delhi and is 25 years old.
1: Bob lives in Mumbai and is 30 years old.
2: Charlie lives in Chennai and is 35 years old.

In [38]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f"{row.Name} lives in {row.City}, and is {row.Age} years old.", end='\n\n')

Pandas(Index=0, Name='Alice', Age=25, City='Delhi')
0
Alice lives in Delhi, and is 25 years old.

Pandas(Index=1, Name='Bob', Age=30, City='Mumbai')
1
Bob lives in Mumbai, and is 30 years old.

Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie lives in Chennai, and is 35 years old.

In [ ]:
# Iterating Over Columns

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].values, end='\n\n')

Column: Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

Column: Age
[25 30 35]

Column: City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

In [41]:
list(df.columns)

['Name', 'Age', 'City']

In [42]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

# Conditional Example: Add Column with Custom Logic

Based on age column, i want to create a new column that will classify people as 'young' or 'senior'

In [ ]:
categories = []

# Loops

for idx, row in df.iterrows():
    print(row)
    print(row['Age'])

    if row['Age'] < 40 :
        categories.append("young")
    else :
        categories.append("senior")

df['Category'] = categories

df.head()

Name    Alice
Age        25
City    Delhi
Name: 0, dtype: object
25
Name       Bob
Age         30
City    Mumbai
Name: 1, dtype: object
30
Name    Charlie
Age          35
City    Chennai
Name: 2, dtype: object
35

      Name  Age     City Category
0    Alice   25    Delhi    young
1      Bob   30   Mumbai    young
2  Charlie   35  Chennai    young

# Better Way: Vectorized / Apply

In [50]:
df['Category_vectorized_1'] = df['Age'].apply(lambda age : 'young' if age < 40 else 'senior')

df['Category_vectorized_1'].head()

0    young
1    young
2    young
Name: Category_vectorized_1, dtype: str

In [51]:
categorize_age_lambda = lambda age : 'young' if age < 40 else 'senior'

df['Category_vectorized_2'] = df['Age'].apply(categorize_age_lambda)

df['Category_vectorized_2'].head()

0    young
1    young
2    young
Name: Category_vectorized_2, dtype: str

In [52]:
def categorize_age_function(age):
    # if age < 40:
    #     return 'young'
    # else :
    #     return 'senior'
    return 'young' if age < 40 else 'senior'

df['Category_vectorized_3'] = df['Age'].apply(categorize_age_function)

df['Category_vectorized_3'].head()

0    young
1    young
2    young
Name: Category_vectorized_3, dtype: str

In [53]:
df.head()

,Name,Age,City,Category,Category_vectorized_1,Category_vectorized_2,Category_vectorized_3
0,Alice,25,Delhi,young,young,young,young
1,Bob,30,Mumbai,young,young,young,young
2,Charlie,35,Chennai,young,young,young,young

In [60]:
for i in df[['Age', 'City']].iterrows():
    print(i)

(0, Age        25
City    Delhi
Name: 0, dtype: object)
(1, Age         30
City    Mumbai
Name: 1, dtype: object)
(2, Age          35
City    Chennai
Name: 2, dtype: object)

In [64]:
df.columns

Index(['Name', 'Age', 'City', 'Category', 'Category_vectorized_1',
       'Category_vectorized_2', 'Category_vectorized_3'],
      dtype='str')

In [66]:
def check_if_delhi_and_young(row):
    print(row)
    city = row['City']
    age = row['Age']
    if city == 'Delhi':
        if age < 40:
            return True
        else :
            return False
    else:
        return False
    # return 'young' if age < 40 else 'senior'

df['If_young_and_from_delhi'] = df.apply(check_if_delhi_and_young, axis=1)

Name                     Alice
Age                         25
City                     Delhi
Category                 young
Category_vectorized_1    young
Category_vectorized_2    young
Category_vectorized_3    young
Name: 0, dtype: object
Name                        Bob
Age                          30
City                     Mumbai
Category                  young
Category_vectorized_1     young
Category_vectorized_2     young
Category_vectorized_3     young
Name: 1, dtype: object
Name                     Charlie
Age                           35
City                     Chennai
Category                   young
Category_vectorized_1      young
Category_vectorized_2      young
Category_vectorized_3      young
Name: 2, dtype: object

In [67]:
df.head()

,Name,Age,City,Category,Category_vectorized_1,Category_vectorized_2,Category_vectorized_3,If_young_and_from_delhi
0,Alice,25,Delhi,young,young,young,young,True
1,Bob,30,Mumbai,young,young,young,young,False
2,Charlie,35,Chennai,young,young,young,young,False

In [ ]:
# # axis = 0
# keep column constant and get all rows

# # axis = 1
# keep row constant and get all columns

# Sorting in Pandas

Sorting helps you organize your data for better readability, analysis, and logical operations — whether by index or actual data values.

### Why Sorting Matters

You might want to:

- See top-performing products (e.g., highest sales)

- Order records by name/date

- Prepare data before merging or visualizing

### Two Main Types of Sorting
1. sort_values() → Sort by data values
2. sort_index() → Sort by index (row or column labels)

# 1. sort_values() → Sort by data values

# syntax

```bash
DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last')
```

| Argument      | Purpose                                 |
| ------------- | --------------------------------------- |
| `by`          | Column label(s) to sort by              |
| `axis`        | 0 = rows (default), 1 = columns         |
| `ascending`   | True = low to high, False = high to low |
| `inplace`     | True = modify current object            |
| `na_position` | 'first' or 'last' for NaNs              |

In [ ]:
# Example of inplace

class Cal:
    def __init__(self, a):
        self.a = a
    def add(self, b):
        c = self.a + b
        return c
    def inplace_add(self, b):
        self.a = self.a + b
        return self.a

In [69]:
c_cal = Cal(10)

In [70]:
c_cal.a

10

In [71]:
c_cal.add(10)

20

In [ ]:
c_cal.a = c_cal.add(10) # inplace False

In [73]:
c_cal.a

20

In [ ]:
c_cal.inplace_add(10) # inplace True

30

In [ ]:
c_cal.a

30

In [76]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [77]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [79]:
sorted_df = df.sort_values(by='Age')
print(sorted_df[['Name', 'Age']].head(10))

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83
831  Richards, Master. George Sibley  0.83
305   Allison, Master. Hudson Trevor  0.92
386  Goodwin, Master. Sidney Leonard  1.00
172     Johnson, Miss. Eleanor Ileen  1.00
183        Becker, Master. Richard F  1.00

In [80]:
print(sorted_df[['Name', 'Age']].tail(10))

                                             Name  Age
832                                Saad, Mr. Amin  NaN
837                           Sirota, Mr. Maurice  NaN
839                          Marechal, Mr. Pierre  NaN
846                      Sage, Mr. Douglas Bullen  NaN
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  NaN
859                              Razi, Mr. Raihed  NaN
863             Sage, Miss. Dorothy Edith "Dolly"  NaN
868                   van Melkebeke, Mr. Philemon  NaN
878                            Laleff, Mr. Kristo  NaN
888      Johnston, Miss. Catherine Helen "Carrie"  NaN

In [81]:
sorted_df.iloc[200:300,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
395,396,0,3,"Johansson, Mr. Erik",male,22.0,0,0,350052,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
134,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,NaN,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S

In [82]:
print(df['Age'].dtype)

float64

In [83]:
df['Age'] = df['Age'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [84]:
df['Age'] = df['Age'].fillna(0).astype('int64')

In [85]:
print(df[['Name', 'Age']].tail(10))

                                         Name  Age
881                        Markun, Mr. Johann   33
882              Dahlberg, Miss. Gerda Ulrika   22
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

In [86]:
sorted_df = df.sort_values(by='Age')
print(sorted_df[['Name', 'Age']].tail(20))

                                          Name  Age
625                      Sutton, Mr. Frederick   61
570                         Harris, Mr. George   62
829  Stone, Mrs. George Nelson (Martha Evelyn)   62
252                  Stead, Mr. William Thomas   62
555                         Wright, Mr. George   62
275          Andrews, Miss. Kornelia Theodosia   63
483                     Turkula, Mrs. (Hedwig)   63
545               Nicholson, Mr. Arthur Ernest   64
438                          Fortune, Mr. Mark   64
54              Ostby, Mr. Engelhart Cornelius   65
456                  Millet, Mr. Francis Davis   65
280                           Duane, Mr. Frank   65
33                       Wheadon, Mr. Edward H   66
116                       Connors, Mr. Patrick   70
745               Crosby, Capt. Edward Gifford   70
672                Mitchell, Mr. Henry Michael   70
493                    Artagaveytia, Mr. Ramon   71
96                   Goldschmidt, Mr. George B   71
851                        Svensson, Mr. Johan   74
630       Barkworth, Mr. Algernon Henry Wilson   80

# Example 2: Sort by multiple columns

First sort by Pclass (ascending), then by Fare (descending)

In [87]:
df_sorted = df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

In [88]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S

# 2. sort_index() – Sorting by index

This is useful when you’ve set a meaningful index and want to restore or arrange it.

```bash
DataFrame.sort_index(axis=0, ascending=True, inplace=False)
```

axis=0 → Sort rows

axis=1 → Sort columns

In [89]:
df_sort_2 = df.set_index('PassengerId')
df_sorted_by_index = df_sort_2.sort_index()

In [91]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [90]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

# Sorting Columns Alphabetically

In [92]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [93]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [95]:
df[['Ticket', 'Name']]

               Ticket                                               Name
0           A/5 21171                            Braund, Mr. Owen Harris
1            PC 17599  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    STON/O2. 3101282                             Heikkinen, Miss. Laina
3              113803       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              373450                           Allen, Mr. William Henry
..                ...                                                ...
886            211536                              Montvila, Rev. Juozas
887            112053                       Graham, Miss. Margaret Edith
888        W./C. 6607           Johnston, Miss. Catherine Helen "Carrie"
889            111369                              Behr, Mr. Karl Howell
890            370376                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [96]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [97]:
df_sorted = df[sorted(df.columns)]

df_sorted.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# Working with Text Data in Pandas

In [99]:
# Lowercase
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [100]:
# Uppercase
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [101]:
# Capitalize
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [102]:
# String Length
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64